"""initial schema

Revision ID: a95b82a8119e
Revises: 
Create Date: 2026-02-12 14:34:16.689075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a95b82a8119e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anime',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('provider', sa.Enum('MAL', 'ANILIST', name='provider_enum'), nullable=False),
    sa.Column('provider_anime_id', sa.Integer(), nullable=False),
    sa.Column('provider_rating', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('anime_type', sa.Enum('OVA', 'TV', 'ONA', 'MOVIE', 'SPECIAL', 'MUSIC', 'UNKNOWN', name='anime_type_enum'), nullable=False),
    sa.Column('status', sa.Enum('COMPLETED', 'AIRING', 'ANNOUNCED', name='anime_status_enum'), nullable=False),
    sa.Column('episode_count', sa.Integer(), nullable=True),
    sa.Column('start_year', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_anime_id', name='uq_anime_provider_provider_anime_id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.Enum('MAL', 'ANILIST', name='provider_enum'), nullable=False),
    sa.Column('provider_username', sa.String(), nullable=False),
    sa.Column('provider_user_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_username', name='uq_provider_username'),
    sa.UniqueConstraint('public_id')
    )
    op.create_table('user_anime_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('anime_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('WATCHING', 'WATCHED', 'ON_HOLD', 'DROPPED', 'PLAN_TO_WATCH', name='entry_status_enum'), nullable=False),
    sa.Column('score', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['anime_id'], ['anime.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'anime_id', name='uq_userid_animeid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_anime_entries')
    op.drop_table('users')
    op.drop_table('anime')
    # ### end Alembic commands ###
